directories:
  output: release
  buildResources: build
appId: com.Astra.astra
productName: Astra
files:
  - filter:
      - dist/
      - electron/
      - '!node_modules/@tailwindcss/oxide-wasm32-wasi/**/*'
win:
  target: nsis
mac:
  target: dmg
linux:
  target: AppImage
electronVersion: 37.3.0
